/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: v1
 */

export interface AccessibilityIssueGroupDTO {
  count?: number;
  /** @nullable */
  currentValues?: string[] | null;
  /** @nullable */
  examples?: string[] | null;
  /** @nullable */
  ruleType?: string | null;
  /** @nullable */
  suggestion?: string | null;
}
