/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: v1
 */
import type { RoundTypeDTO } from './roundTypeDTO';

export interface CreateRoundRequestDTO {
  /** @nullable */
  instructions?: string | null;
  orderIndex?: number;
  timeInMinutes?: number;
  /** @minLength 1 */
  title: string;
  type: RoundTypeDTO;
}
