/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: v1
 */
import type { FlashcardReviewDTO } from './flashcardReviewDTO';

export interface FlashcardDTO {
  /** @nullable */
  answer: string | null;
  /** @nullable */
  conceptId?: number | null;
  createdAt?: string;
  flashcardSetId?: number;
  id?: number;
  importance?: number;
  isMarkedForReview?: boolean;
  lastReviewDate?: string;
  nextReviewDate?: string;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  question: string | null;
  reviewCount?: number;
  /** @nullable */
  reviewHistory?: FlashcardReviewDTO[] | null;
  successCount?: number;
}
