/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: v1
 */
import type { RoundResponseDTO } from './roundResponseDTO';

export interface GameTemplateResponseDTO {
  createdAt: string;
  /** @nullable */
  description?: string | null;
  id: number;
  isPublic: boolean;
  /** @nullable */
  name: string | null;
  /** @nullable */
  rounds: RoundResponseDTO[] | null;
}
