/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: v1
 */

export interface GenerateFlashcardsRequestDTO {
  /** @minLength 1 */
  content: string;
  /** @nullable */
  model?: string | null;
  /** @nullable */
  provider?: string | null;
  /** @minLength 1 */
  title: string;
}
