/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: v1
 */

export interface HealthStatusDTO {
  /** @nullable */
  environment: string | null;
  /** @nullable */
  status: string | null;
  timestamp?: string;
  /** @nullable */
  version: string | null;
}
