/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: v1
 */

export type PutApiFlashcardsFlashcardIdParams = {
question?: string;
answer?: string;
importance?: number;
};
