/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: v1
 */
import type { ConceptDTO } from './conceptDTO';
import type { StudyStructureDTO } from './studyStructureDTO';

export interface RelationshipDTO {
  id?: number;
  sourceConcept?: ConceptDTO;
  sourceConceptId?: number;
  studyStructure?: StudyStructureDTO;
  studyStructureId?: number;
  targetConcept?: ConceptDTO;
  targetConceptId?: number;
  /** @nullable */
  type?: string | null;
}
