/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: v1
 */
import type { RoundTypeDTO } from './roundTypeDTO';

export interface RoundRequestDTO {
  type?: RoundTypeDTO;
}
