/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: v1
 */
import type { ConceptDTO } from './conceptDTO';
import type { RelationshipDTO } from './relationshipDTO';

export interface StudyStructureDTO {
  /** @nullable */
  concepts?: ConceptDTO[] | null;
  createdAt?: string;
  id?: number;
  lastModified?: string;
  /** @nullable */
  originalContent: string | null;
  /** @nullable */
  relationships?: RelationshipDTO[] | null;
  /** @nullable */
  title: string | null;
}
