/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: v1
 */

export interface TeamResponseDTO {
  /** @nullable */
  color: string | null;
  id: number;
  /** @nullable */
  name: string | null;
  score: number;
}
