/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: v1
 */
import type { AccessibilityIssueGroupDTO } from './accessibilityIssueGroupDTO';

export interface AccessibilitySectionDTO {
  /** @nullable */
  description?: string | null;
  /** @nullable */
  impact?: string | null;
  /** @nullable */
  issueGroups?: AccessibilityIssueGroupDTO[] | null;
  scoreImpact?: number;
  /** @nullable */
  section?: string | null;
  /** @nullable */
  title?: string | null;
  totalIssues?: number;
}
