/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: v1
 */

export interface AccessibilityIssueDTO {
  /** @nullable */
  currentValue?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  element?: string | null;
  /** @nullable */
  impact?: string | null;
  /** @nullable */
  ruleType?: string | null;
  scoreImpact?: number;
  /** @nullable */
  section?: string | null;
  /** @nullable */
  suggestion?: string | null;
}
