/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: v1
 */
import type { AccessibilityIssueDTO } from './accessibilityIssueDTO';
import type { AccessibilitySectionDTO } from './accessibilitySectionDTO';

export interface AnalysisResultDTO {
  /** @nullable */
  detailedIssues?: AccessibilityIssueDTO[] | null;
  score?: number;
  /** @nullable */
  sections?: AccessibilitySectionDTO[] | null;
}
