/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: v1
 */

export interface AnalyzeRequestDTO {
  /** @nullable */
  content: string | null;
  /** @nullable */
  model: string | null;
  /** @nullable */
  provider: string | null;
  /** @nullable */
  title: string | null;
}
