/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: v1
 */
import type { StudyStructureDTO } from './studyStructureDTO';

export interface ConceptDTO {
  /** @nullable */
  content: string | null;
  id?: number;
  level?: number;
  order?: number;
  studyStructure?: StudyStructureDTO;
  studyStructureId?: number;
}
