/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: v1
 */

export interface CreateTeamRequestDTO {
  /** @minLength 1 */
  color: string;
  /** @minLength 1 */
  name: string;
}
