/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: v1
 */
import type { FlashcardDTO } from './flashcardDTO';

export interface FlashcardSetDTO {
  createdAt?: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  flashcards?: FlashcardDTO[] | null;
  id?: number;
  lastModified?: string;
  /** @nullable */
  studyStructureId?: number | null;
  /** @nullable */
  title: string | null;
}
