/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: v1
 */

export interface FlashcardReviewDTO {
  /** @nullable */
  comment?: string | null;
  flashcardId?: number;
  id?: number;
  isCorrect?: boolean;
  reviewedAt?: string;
}
