/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: v1
 */

export type GameStatusDTO = typeof GameStatusDTO[keyof typeof GameStatusDTO];


 
export const GameStatusDTO = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
