/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: v1
 */

export type RoundStatusDTO = typeof RoundStatusDTO[keyof typeof RoundStatusDTO];


 
export const RoundStatusDTO = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
