/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: v1
 */

export interface RoundItemResponseDTO {
  /** @nullable */
  artist: string | null;
  /** @nullable */
  extraInfo?: string | null;
  id: number;
  isAnswerRevealed?: boolean;
  orderIndex: number;
  points: number;
  /** @nullable */
  spotifyId?: string | null;
  /** @nullable */
  title: string | null;
}
