/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: v1
 */

export interface ScrapeUrlResponseDTO {
  /** @nullable */
  html?: string | null;
  loadTimeSeconds?: number;
  /** @nullable */
  screenshot?: string | null;
}
