/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: v1
 */

export type SongLanguageDTO = typeof SongLanguageDTO[keyof typeof SongLanguageDTO];


 
export const SongLanguageDTO = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
