/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: v1
 */

export interface W3ValidationMessageDTO {
  /** @nullable */
  message?: string | null;
  /** @nullable */
  type?: string | null;
}
