/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: v1
 */
import type { W3ValidationMessageDTO } from './w3ValidationMessageDTO';

export interface W3ValidationResponseDTO {
  /** @nullable */
  messages?: W3ValidationMessageDTO[] | null;
}
